export default {
    mainurl: 'http://203.109.113.162:35555/castpro/public/api/',
    // mainurl: 'http://203.109.113.162:9098/castpro/public/api/',   ///Developer URL marmik
    // mainurl: 'http://203.109.113.162:5055/castpro/public/api/',   ///Testing URL
    // mainurl: 'http://ec2-52-15-140-180.us-east-2.compute.amazonaws.com/castpro/public/api/',   ///Testing URL
    // mainurl: 'http://castpro.live/api/',   ///Live URL
    // mainurl: 'http://api.castpro.live/api/',   ///Live URL new 5/01/2022

    // Profile API
    Register: 'register',
    login: 'login',
    Facebooklogin: 'facebookLogin',
    Upload: 'testAPI',
    userVerifyotp: 'userVerify',
    Chnagepassword: 'changePassword',
    Actorprofile: 'getProfile',
    Directorgetprofile: 'getDirectorProfile',
    Directorupdateprofile: 'updateDirectorDetails',
    Termsandcondition: 'getTermsAndConditions',
    Getsocialmedia: 'getSocialMedia',
    GetStateAndCity: 'getStateAndCities',
    UpdateActorBio: 'updateActorBio',
    ActorPhootAddDelete: 'actorImageAddDelete',
    ActorVideo: 'actorVideoAddDelete',
    ActorUpdateworklink: 'updateActorWorkLinks',
    UpdateDirectorAcceptTCStatus: 'updateDirectorAcceptTCStatus',
    Getcountrycode: 'getCountriesCode',
    GetLanguage: 'getLanguage',
    GetSkill: 'getSkill',
    AllProject: 'getAllProjects',
    SearchProjectandRole: 'searchRoles',
    ViewProjectDetail: 'viewProjectById',
    RoleDetail: 'roleDetails',
    ProfileReqeustlist: 'profileRequestList',
    ActionProfileRequestlist: 'actionForProfileRequest',
    AuditionRequestlist: 'getAuditionRequestList',
    AudtionAceeptReject: 'actionAuditionRequest',
    UploadAudition: 'addRoleAudition',
    GetAuditionlist: 'getAuditionListForActor',
    ViewAudition: 'viewRoleAuditionDetail',
    AuditionComment: 'auditionComment',
    GetShortlist: 'getShortlistAudition',
    ViewDirectorProfile: 'artistViewDirectorProfile',
    GetNotification: 'getNotificationList',
    ReadNotificaion: 'readNotification',
    Unreadcoiunt: 'getUnreadNotificationListCount',
    Aboutus: 'getAboutUs',
    Notification: 'updateNotificationStatus',
    ProjectTypes: 'getProjectTypes',
    GetArtistDashboard: 'getArtistDashboard',
    ProjectListing: 'projectListing',
    AddArtistphot: 'addArtistPhoto',
    AuditionDetaillisting: 'auditionDetailListing',
    Audtiondetailbyid: 'auditionDetailByID',
    SearchCity: 'searchCities',
    AddSocialLink: 'addSocialLinks',
    AddWorklink: 'addDirectorWorkLinks',
    ChangePAssworduser: 'changeAppUserPassword',
    ArtistPDF: 'artistProfilePdf',
    UpdateWorklink: 'updateorDeleteWorkLinks',
    UpdateRoleAduitionMedaiStatus: 'updateProjectRoleAuditionMediaStatus',
    GetActorAuditionUpload: 'getActorInprogressAuditionMediaStatus',
    UpdateActorVideo: 'updateActorIntroAndWorkLink',
    GetActorIntroandWrokVide: 'getActorIntroVideoAndWorklink',
    PaymentCheckStatus: 'checkUserPaymentStatus'
};

